version: '3.7'
services:
  pg:
    image: 'postgres:14-alpine'
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: srdb
      POSTGRES_HOST_AUTH_METHOD: trust
      NODE_ENV: dev
    ports:
      - '5433:5432'
    volumes:
      - ./src/server/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
